@startuml is002_LtpUpdateCauseAddToLink
skinparam responseMessageBelowArrow true

title
LtpUpdateMightCauseOperationClientBeingAddedToLink
end title

participant "Requestor" as requestor
participant "ALT://v1/update-ltp" as altUpdateLtp
participant "ALT://v1/add-operation-client-to-link" as altAddClientToLink


@enduml